# Generated by ChatGPT
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_user_coordinador"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(max_length=30, choices=[
                ("ADMIN", "Administrador"),
                ("COORDINADOR_ELECTORAL", "Coordinador Electoral"),
                ("LIDER", "Líder"),
                ("COLABORADOR", "Colaborador"),
                ("CANDIDATO", "Candidato"),
            ], default="COLABORADOR"),
        ),
    ]
