# Generated by ChatGPT
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_role_length"),
        ("polling", "0002_pollingstation_details"),
    ]

    operations = [
        migrations.CreateModel(
            name="ElectoralWitnessAssignment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("mesas", models.JSONField()),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                (
                    "creado_por",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="testigos_creados",
                        to="accounts.user",
                    ),
                ),
                (
                    "puesto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="asignaciones_testigos",
                        to="polling.pollingstation",
                    ),
                ),
                (
                    "testigo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="asignaciones_testigo",
                        to="accounts.user",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="electoralwitnessassignment",
            constraint=models.UniqueConstraint(fields=("testigo",), name="unique_testigo_assignment"),
        ),
    ]
