# Generated by Django 4.2.27 on 2025-12-24 02:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_role_length'),
        ('accounts', '0006_user_meta_votantes_positive'),
    ]

    operations = [
    ]
