# Generated by Django 4.2.27 on 2025-12-24 02:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_testigo_assignment'),
        ('accounts', '0007_merge_20251223_2103'),
    ]

    operations = [
    ]
