# Generated by Django 4.2.27 on 2025-12-24 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_electoral_witness_release_audit'),
        ('accounts', '0008_merge_20251223_2112'),
    ]

    operations = [
    ]
