# Generated by Django 5.2.8 on 2026-03-12 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_merge_20251223_2209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrador'), ('COORDINADOR_ELECTORAL', 'Coordinador Electoral'), ('TESTIGO_ELECTORAL', 'Testigo Electoral'), ('LIDER', 'Líder'), ('COLABORADOR', 'Colaborador'), ('CANDIDATO', 'Candidato')], default='COLABORADOR', max_length=30),
        ),
    ]
