# Generated by Django 5.2.8 on 2026-02-27 04:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('territory', '0003_zonaasignacion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(max_length=50)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('entidad_id', models.IntegerField()),
                ('accion', models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('ANULAR', 'Anular')], max_length=20)),
                ('antes', models.JSONField(blank=True, null=True)),
                ('despues', models.JSONField(blank=True, null=True)),
                ('motivo', models.TextField(blank=True, null=True)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BudgetPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo_inicio', models.DateField()),
                ('periodo_fin', models.DateField()),
                ('categoria', models.CharField(choices=[('PUBLICIDAD', 'Publicidad'), ('LOGISTICA', 'Logística'), ('TRANSPORTE', 'Transporte'), ('EVENTOS', 'Eventos'), ('OPERATIVO', 'Operativo'), ('JURIDICO', 'Jurídico'), ('DIGITAL', 'Digital'), ('OTRO', 'Otro')], max_length=50)),
                ('monto_presupuestado', models.DecimalField(decimal_places=2, max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='budgets_created', to=settings.AUTH_USER_MODEL)),
                ('departamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to='territory.departamento')),
                ('municipio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to='territory.municipio')),
            ],
        ),
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('GASTO', 'Gasto'), ('APORTE', 'Aporte')], max_length=20)),
                ('categoria', models.CharField(choices=[('PUBLICIDAD', 'Publicidad'), ('LOGISTICA', 'Logística'), ('TRANSPORTE', 'Transporte'), ('EVENTOS', 'Eventos'), ('OPERATIVO', 'Operativo'), ('JURIDICO', 'Jurídico'), ('DIGITAL', 'Digital'), ('OTRO', 'Otro')], max_length=50)),
                ('descripcion', models.TextField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=15)),
                ('fecha', models.DateField()),
                ('medio_pago', models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('TRANSFERENCIA', 'Transferencia'), ('TARJETA', 'Tarjeta'), ('OTRO', 'Otro')], max_length=50)),
                ('proveedor', models.CharField(blank=True, max_length=255, null=True)),
                ('comprobante', models.FileField(blank=True, null=True, upload_to='investments/comprobantes/')),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('ANULADO', 'Anulado')], default='ACTIVO', max_length=20)),
                ('motivo_anulacion', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('departamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='investments', to='territory.departamento')),
                ('municipio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='investments', to='territory.municipio')),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='investments_registered', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
