# Generated by Django 5.2.8 on 2025-11-19 03:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("territory", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Necesidad",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Encuesta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_hora", models.DateTimeField(auto_now_add=True)),
                (
                    "nombre_ciudadano",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                ("telefono", models.CharField(max_length=30)),
                (
                    "tipo_vivienda",
                    models.CharField(
                        choices=[
                            ("PROPIA", "Propia"),
                            ("ARRIENDO", "Arriendo"),
                            ("FAMILIAR", "Familiar"),
                            ("OTRO", "Otro"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "rango_edad",
                    models.CharField(
                        choices=[
                            ("14-25", "14-25"),
                            ("26-40", "26-40"),
                            ("41-60", "41-60"),
                            ("60+", "60+"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "ocupacion",
                    models.CharField(
                        choices=[
                            ("ESTUDIANTE", "Estudiante"),
                            ("EMPLEADO", "Empleado"),
                            ("INDEPENDIENTE", "Independiente"),
                            ("DESEMPLEADO", "Desempleado"),
                            ("AGRICULTOR", "Agricultor"),
                            ("OTRO", "Otro"),
                        ],
                        max_length=20,
                    ),
                ),
                ("tiene_ninos", models.BooleanField(default=False)),
                ("tiene_adultos_mayores", models.BooleanField(default=False)),
                ("tiene_personas_con_discapacidad", models.BooleanField(default=False)),
                ("comentario_problema", models.TextField(blank=True, null=True)),
                ("consentimiento", models.BooleanField(default=False)),
                (
                    "lat",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "lon",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                ("caso_critico", models.BooleanField(default=False)),
                (
                    "colaborador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="encuestas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "zona",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="encuestas",
                        to="territory.zona",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CasoCiudadano",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nivel_prioridad",
                    models.CharField(
                        choices=[
                            ("BAJA", "Baja"),
                            ("MEDIA", "Media"),
                            ("ALTA", "Alta"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("REGISTRADO", "Registrado"),
                            ("EN_REVISION", "En revisión"),
                            ("ATENDIDO", "Atendido"),
                        ],
                        default="REGISTRADO",
                        max_length=15,
                    ),
                ),
                ("notas_seguimiento", models.TextField(blank=True, null=True)),
                (
                    "encuesta",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="caso",
                        to="surveys.encuesta",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EncuestaNecesidad",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "prioridad",
                    models.IntegerField(
                        choices=[(1, "Alta"), (2, "Media"), (3, "Baja")]
                    ),
                ),
                (
                    "encuesta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="necesidades",
                        to="surveys.encuesta",
                    ),
                ),
                (
                    "necesidad",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="surveys.necesidad",
                    ),
                ),
            ],
            options={
                "unique_together": {("encuesta", "prioridad")},
            },
        ),
    ]
