# Generated by ChatGPT
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("surveys", "0004_encuesta_candidato_fields"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="encuesta",
            name="primer_nombre",
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name="encuesta",
            name="segundo_nombre",
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name="encuesta",
            name="primer_apellido",
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name="encuesta",
            name="segundo_apellido",
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name="encuesta",
            name="correo",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="encuesta",
            name="sexo",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="encuesta",
            name="pais",
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name="encuesta",
            name="departamento",
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name="encuesta",
            name="municipio",
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name="encuesta",
            name="puesto",
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name="encuesta",
            name="mesa",
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name="encuesta",
            name="estado_validacion",
            field=models.CharField(
                choices=[
                    ("PENDIENTE", "Pendiente de validación"),
                    ("VALIDADO", "Validado"),
                    ("NO_VALIDADO", "No validado"),
                ],
                default="PENDIENTE",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="CedulaValidationMaster",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("cedula", models.CharField(max_length=15, unique=True)),
                ("pais", models.CharField(blank=True, max_length=80, null=True)),
                ("departamento", models.CharField(blank=True, max_length=80, null=True)),
                ("municipio", models.CharField(blank=True, max_length=80, null=True)),
                ("puesto", models.CharField(blank=True, max_length=120, null=True)),
                ("mesa", models.CharField(blank=True, max_length=40, null=True)),
                ("primer_nombre", models.CharField(blank=True, max_length=80, null=True)),
                ("segundo_nombre", models.CharField(blank=True, max_length=80, null=True)),
                ("primer_apellido", models.CharField(blank=True, max_length=80, null=True)),
                ("segundo_apellido", models.CharField(blank=True, max_length=80, null=True)),
                ("telefono", models.CharField(blank=True, max_length=30, null=True)),
                ("correo", models.EmailField(blank=True, max_length=254, null=True)),
                ("sexo", models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={"ordering": ["cedula"]},
        ),
        migrations.CreateModel(
            name="SurveyValidationAudit",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("cedula", models.CharField(max_length=15)),
                ("rol_usuario", models.CharField(max_length=20)),
                ("fecha_hora", models.DateTimeField(auto_now_add=True)),
                (
                    "tipo_validacion",
                    models.CharField(
                        choices=[("INDIVIDUAL", "Individual"), ("MASIVA", "Masiva")],
                        max_length=15,
                    ),
                ),
                ("datos_antes", models.JSONField()),
                ("datos_nuevos", models.JSONField(blank=True, null=True)),
                (
                    "estado_resultado",
                    models.CharField(
                        choices=[
                            ("CONFIRMADO", "Confirmado"),
                            ("CANCELADO", "Cancelado"),
                            ("SIN_COINCIDENCIA", "Sin coincidencia"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "registro",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="auditorias_validacion",
                        to="surveys.encuesta",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"ordering": ["-fecha_hora"]},
        ),
    ]
