# Generated by ChatGPT
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("surveys", "0005_validacion_cedula"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="encuesta",
            name="nombre_ciudadano",
        ),
    ]
