# Generated by ChatGPT
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("surveys", "0006_remove_nombre_ciudadano"),
    ]

    operations = [
        migrations.AddField(
            model_name="surveyvalidationaudit",
            name="tipo_evento",
            field=models.CharField(
                choices=[("VALIDACION", "Validación"), ("EDICION_MANUAL", "Edición manual")],
                default="VALIDACION",
                max_length=20,
            ),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name="surveyvalidationaudit",
            name="estado_validacion_anterior",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="surveyvalidationaudit",
            name="estado_validacion_nuevo",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
