# Generated by ChatGPT
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("surveys", "0007_audit_manual_edit"),
    ]

    operations = [
        migrations.AddField(
            model_name="encuesta",
            name="telefono_alternativo",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
