# Generated by Django 5.2.8 on 2026-02-27 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0008_telefono_alternativo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='encuesta',
            name='ocupacion',
        ),
        migrations.RemoveField(
            model_name='encuesta',
            name='rango_edad',
        ),
        migrations.RemoveField(
            model_name='encuesta',
            name='tiene_adultos_mayores',
        ),
        migrations.RemoveField(
            model_name='encuesta',
            name='tiene_ninos',
        ),
        migrations.RemoveField(
            model_name='encuesta',
            name='tiene_personas_con_discapacidad',
        ),
        migrations.RemoveField(
            model_name='encuesta',
            name='tipo_vivienda',
        ),
        migrations.AlterField(
            model_name='encuesta',
            name='estado_validacion',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente de validación'), ('VALIDADO', 'Validado'), ('NO_VALIDADO', 'No validado'), ('VALIDADO_AJUSTADO', 'Validado con ajustes')], default='PENDIENTE', max_length=20),
        ),
    ]
