# Generated by ChatGPT
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PollingStation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("nombre", models.CharField(max_length=255)),
                ("latitud", models.DecimalField(decimal_places=6, max_digits=9)),
                ("longitud", models.DecimalField(decimal_places=6, max_digits=9)),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                (
                    "creado_por",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="polling_stations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-creado_en"],
            },
        ),
        migrations.AddConstraint(
            model_name="pollingstation",
            constraint=models.UniqueConstraint(fields=("nombre", "latitud", "longitud"), name="unique_polling_station"),
        ),
    ]
