# Generated by ChatGPT
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("polling", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="pollingstation",
            name="departamento",
            field=models.CharField(default="", max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="pollingstation",
            name="municipio",
            field=models.CharField(default="", max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="pollingstation",
            name="puesto",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="pollingstation",
            name="mesas",
            field=models.CharField(default="", max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="pollingstation",
            name="direccion",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="pollingstation",
            name="nombre",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.RemoveConstraint(
            model_name="pollingstation",
            name="unique_polling_station",
        ),
        migrations.AddConstraint(
            model_name="pollingstation",
            constraint=models.UniqueConstraint(
                fields=("departamento", "municipio", "puesto", "mesas", "direccion", "latitud", "longitud"),
                name="unique_polling_station",
            ),
        ),
    ]
